services:
  app:
    build: .
    container_name: bd_web_app

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: bd_web_db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bd_web_db
      MYSQL_USER: bduser
      MYSQL_PASSWORD: bdpass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
